# NB you'll need to map "moodle" and "pluginservice" to 127.0.0.1 in your hosts
# file for this to work; you'll also need to allow Moodle to use port 80
version: '2'
services:
  moodle:
    image: res-moodle-plugin_moodle
    build:
      context: ./build-moodle
      dockerfile: Dockerfile-moodle
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
    ports:
      - "80:80"
      - "443:443"
    links:
      - mariadb
    environment:
      # should match the entry under links (above)
      - MYSQL_HOST=mariadb

      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle

      # this is the URL which other services should be able to reach Moodle at
      # from within the docker context and should match the service name;
      # NB this is passed by the Moodle plugin to the pluginservice as the
      # callback URL and also needs to be accessible by the browser (not just
      # the back-end services)
      - MOODLE_URL=http://moodle
    volumes:
      - ./build-moodle/plugin/dist:/var/www/html/repository/res
  mariadb:
    image: res-moodle-plugin_mariadb
    build:
      context: ./build-mariadb
      dockerfile: Dockerfile-mariadb
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
    ports:
      - "6306:3306"
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle
      - MYSQL_ROOT_PASSWORD=moodle
