# copyright BBC 2017
# author    Elliot Smith <elliot.smith@bbc.co.uk>
# license   Apache v2 - http://www.apache.org/licenses/LICENSE-2.0
#
# based on https://hub.docker.com/r/jauer/moodle/ but modified
# for Moodle 3 and PHP 7.* (Ubuntu 14 doesn't support a high enough PHP version
# for Moodle 3); also has some gubbins so it works better with docker-compose

FROM ubuntu:16.04
MAINTAINER Elliot Smith <elliot.smith@bbc.co.uk>

# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive

# This preserves Moodle's data even if the container is destroyed;
# Moodle config.php $CFG->dataroot should be set to this path
VOLUME ["/var/moodledata"]

EXPOSE 80 443

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install mysql-client pwgen curl apache2 postfix netcat git unzip \
    nodejs npm php7.0 php7.0-gd php7.0-intl php7.0-curl php7.0-xml php7.0-zip \
    php7.0-xmlrpc php7.0-mysql libapache2-mod-php7.0 php7.0-cli php7.0-mbstring

# Enable SSL, Moodle requires it
RUN a2enmod ssl && a2ensite default-ssl

ENV MOODLE_URL=${MOODLE_URL} \
    MYSQL_HOST=${MYSQL_HOST} \
    MYSQL_DATABASE=${MYSQL_DATABASE} \
    MYSQL_USER=${MYSQL_USER} \
    MYSQL_PASSWORD=${MYSQL_PASSWORD} \
    PLUGINSERVICE_HOST=${PLUGINSERVICE_HOST}

# Download Moodle tarball;
# get latest URL from https://download.moodle.org/releases/latest/
RUN curl -L -o /tmp/moodle.tgz https://download.moodle.org/stable33/moodle-latest-33.tgz

# Moodle and Apache config and scripts
COPY moodle-config.php /var/www/html/config.php
COPY ./foreground-apache.sh /etc/apache2/foreground-apache.sh
COPY ./run-moodle.sh /run.sh
COPY ./check-database.php /check-database.php

# unpack Moodle, configure it and Apache
RUN cd /tmp && \
    tar zxf moodle.tgz && \
    mv /tmp/moodle/* /var/www/html/ && \
    rm /var/www/html/index.html && \
    chmod +x /etc/apache2/foreground-apache.sh && \
    chmod +x /run.sh && \
    rm /tmp/moodle.tgz

# copy plugin source to appropriate location
COPY res_moodle_plugin_distro_maker /tmp/res_moodle_plugin_distro_maker

# install bower and composer, symlink node
RUN ln -s /usr/bin/nodejs /usr/bin/node && \
    npm install -g bower && \
    curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

RUN echo '{ "allow_root": true }' > /root/.bowerrc && cd /tmp/res_moodle_plugin_distro_maker && composer install && ./vendor/bin/robo all

RUN cp -a /tmp/res_moodle_plugin_distro_maker/dist /var/www/html/repository/res

# set permissions
RUN chown -R www-data:www-data /var/www/html

ENTRYPOINT ["/run.sh"]
CMD ["/etc/apache2/foreground-apache.sh"]
